name: BD Arch
favicon: null
layout_spectrum: 0.96733
typography_spectrum: 0.47577
title: advanced architectural design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6fa4ca'
    - '#000000'
    - '#616a72'
    - '#3b4045'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
