name: BD Arch
favicon: null
layout_spectrum: 0.2944
typography_spectrum: 0.47577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1817'
    - '#847a75'
    - '#ad9d94'
    - '#dfcfc4'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
