name: BD Arch
favicon: null
layout_spectrum: 0.14428
typography_spectrum: 0.52495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f2643'
    - '#6777a8'
    - '#dbc9bf'
    - '#892e2d'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
