name: BD Arch
favicon: null
layout_spectrum: 0.4833658691495657
typography_spectrum: 0.11770350858569145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10243664309382439
  lightness: 0.8858747000340372
  saturation: 0.16074494505301118
  rhythmicContrast: 0.31532267038710415
purpose: []
